version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  scraper:
    build: .
    container_name: instagram_scraper
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://$MONGO_HOST:$MONGO_PORT/$MONGO_DB
      - MONGO_COLLECTION=$MONGO_COLLECTION
      - HASHTAG=$HASHTAG
      - INSTA_USERNAME=$INSTA_USERNAME
      - INSTA_PASSWORD=$INSTA_PASSWORD

volumes:
  mongodb_data:
