version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build: .
    container_name: instagram_scraper
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: instagram
      MONGO_COLLECTION: posts
      HASHTAG: donaldtrump
      MAX_POSTS: 100
      INSTA_USERNAME: votre_nom_utilisateur
      INSTA_PASSWORD: votre_mot_de_passe
    depends_on:
      - mongodb

volumes:
  mongo_data:
